// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/control.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Relay_GetStatus_FullMethodName       = "/vkturn.control.v1.Relay/GetStatus"
	Relay_ListPeers_FullMethodName       = "/vkturn.control.v1.Relay/ListPeers"
	Relay_CreatePeer_FullMethodName      = "/vkturn.control.v1.Relay/CreatePeer"
	Relay_DeletePeer_FullMethodName      = "/vkturn.control.v1.Relay/DeletePeer"
	Relay_ListFlows_FullMethodName       = "/vkturn.control.v1.Relay/ListFlows"
	Relay_GetFlowStats_FullMethodName    = "/vkturn.control.v1.Relay/GetFlowStats"
	Relay_StreamFlowStats_FullMethodName = "/vkturn.control.v1.Relay/StreamFlowStats"
	Relay_StreamFlows_FullMethodName     = "/vkturn.control.v1.Relay/StreamFlows"
)

// RelayClient is the client API for Relay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Relay is the management API the wingsv-panel calls over gRPC to drive a
// vk-turn-proxy node: inspect status and manage the WireGuard/AmneziaWG peers
// that back the tunnel. It is distinct from the DTLS relay data plane and from
// the app self-enroll path (which reaches the panel over its own gRPC).
type RelayClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*Status, error)
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*Peers, error)
	CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*Peer, error)
	DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error)
	ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*Flows, error)
	GetFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (*FlowStats, error)
	// StreamFlowStats pushes a FlowStats snapshot on a fast cadence so the panel
	// shows live speed/traffic without polling each node. Same payload as
	// GetFlowStats; the panel keeps the connection open and reads deltas.
	StreamFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowStats], error)
	// StreamFlows pushes the active-flow list on a fast cadence so the panel's flow
	// graph updates live. Same payload as ListFlows.
	StreamFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flows], error)
}

type relayClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayClient(cc grpc.ClientConnInterface) RelayClient {
	return &relayClient{cc}
}

func (c *relayClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, Relay_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*Peers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Peers)
	err := c.cc.Invoke(ctx, Relay_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*Peer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Peer)
	err := c.cc.Invoke(ctx, Relay_CreatePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePeerResponse)
	err := c.cc.Invoke(ctx, Relay_DeletePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) ListFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (*Flows, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flows)
	err := c.cc.Invoke(ctx, Relay_ListFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) GetFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (*FlowStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowStats)
	err := c.cc.Invoke(ctx, Relay_GetFlowStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayClient) StreamFlowStats(ctx context.Context, in *GetFlowStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FlowStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[0], Relay_StreamFlowStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFlowStatsRequest, FlowStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_StreamFlowStatsClient = grpc.ServerStreamingClient[FlowStats]

func (c *relayClient) StreamFlows(ctx context.Context, in *ListFlowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Flows], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Relay_ServiceDesc.Streams[1], Relay_StreamFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListFlowsRequest, Flows]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_StreamFlowsClient = grpc.ServerStreamingClient[Flows]

// RelayServer is the server API for Relay service.
// All implementations must embed UnimplementedRelayServer
// for forward compatibility.
//
// Relay is the management API the wingsv-panel calls over gRPC to drive a
// vk-turn-proxy node: inspect status and manage the WireGuard/AmneziaWG peers
// that back the tunnel. It is distinct from the DTLS relay data plane and from
// the app self-enroll path (which reaches the panel over its own gRPC).
type RelayServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*Status, error)
	ListPeers(context.Context, *ListPeersRequest) (*Peers, error)
	CreatePeer(context.Context, *CreatePeerRequest) (*Peer, error)
	DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error)
	ListFlows(context.Context, *ListFlowsRequest) (*Flows, error)
	GetFlowStats(context.Context, *GetFlowStatsRequest) (*FlowStats, error)
	// StreamFlowStats pushes a FlowStats snapshot on a fast cadence so the panel
	// shows live speed/traffic without polling each node. Same payload as
	// GetFlowStats; the panel keeps the connection open and reads deltas.
	StreamFlowStats(*GetFlowStatsRequest, grpc.ServerStreamingServer[FlowStats]) error
	// StreamFlows pushes the active-flow list on a fast cadence so the panel's flow
	// graph updates live. Same payload as ListFlows.
	StreamFlows(*ListFlowsRequest, grpc.ServerStreamingServer[Flows]) error
	mustEmbedUnimplementedRelayServer()
}

// UnimplementedRelayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServer struct{}

func (UnimplementedRelayServer) GetStatus(context.Context, *GetStatusRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRelayServer) ListPeers(context.Context, *ListPeersRequest) (*Peers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedRelayServer) CreatePeer(context.Context, *CreatePeerRequest) (*Peer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePeer not implemented")
}
func (UnimplementedRelayServer) DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePeer not implemented")
}
func (UnimplementedRelayServer) ListFlows(context.Context, *ListFlowsRequest) (*Flows, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlows not implemented")
}
func (UnimplementedRelayServer) GetFlowStats(context.Context, *GetFlowStatsRequest) (*FlowStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowStats not implemented")
}
func (UnimplementedRelayServer) StreamFlowStats(*GetFlowStatsRequest, grpc.ServerStreamingServer[FlowStats]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFlowStats not implemented")
}
func (UnimplementedRelayServer) StreamFlows(*ListFlowsRequest, grpc.ServerStreamingServer[Flows]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFlows not implemented")
}
func (UnimplementedRelayServer) mustEmbedUnimplementedRelayServer() {}
func (UnimplementedRelayServer) testEmbeddedByValue()               {}

// UnsafeRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServer will
// result in compilation errors.
type UnsafeRelayServer interface {
	mustEmbedUnimplementedRelayServer()
}

func RegisterRelayServer(s grpc.ServiceRegistrar, srv RelayServer) {
	// If the following call pancis, it indicates UnimplementedRelayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Relay_ServiceDesc, srv)
}

func _Relay_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_CreatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).CreatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_CreatePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).CreatePeer(ctx, req.(*CreatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_DeletePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).DeletePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_DeletePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).DeletePeer(ctx, req.(*DeletePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_ListFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).ListFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_ListFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).ListFlows(ctx, req.(*ListFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_GetFlowStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlowStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServer).GetFlowStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Relay_GetFlowStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServer).GetFlowStats(ctx, req.(*GetFlowStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relay_StreamFlowStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFlowStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayServer).StreamFlowStats(m, &grpc.GenericServerStream[GetFlowStatsRequest, FlowStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_StreamFlowStatsServer = grpc.ServerStreamingServer[FlowStats]

func _Relay_StreamFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFlowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayServer).StreamFlows(m, &grpc.GenericServerStream[ListFlowsRequest, Flows]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Relay_StreamFlowsServer = grpc.ServerStreamingServer[Flows]

// Relay_ServiceDesc is the grpc.ServiceDesc for Relay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Relay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vkturn.control.v1.Relay",
	HandlerType: (*RelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Relay_GetStatus_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _Relay_ListPeers_Handler,
		},
		{
			MethodName: "CreatePeer",
			Handler:    _Relay_CreatePeer_Handler,
		},
		{
			MethodName: "DeletePeer",
			Handler:    _Relay_DeletePeer_Handler,
		},
		{
			MethodName: "ListFlows",
			Handler:    _Relay_ListFlows_Handler,
		},
		{
			MethodName: "GetFlowStats",
			Handler:    _Relay_GetFlowStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFlowStats",
			Handler:       _Relay_StreamFlowStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamFlows",
			Handler:       _Relay_StreamFlows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/control.proto",
}
