// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/appcontrol.proto

// AppControl is the LOCAL IPC between the WINGS V host app and the embedded
// vk-turn-proxy client (libclient.so), served over a unix domain socket. It
// replaces the older stdin/stdout/cookie-file channels with a typed contract:
// the app pushes VK webview cookies in, and pulls the provisioned WireGuard
// config out.

package appcontrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppControl_SetVKCookies_FullMethodName         = "/vkturn.appcontrol.v1.AppControl/SetVKCookies"
	AppControl_GetVKCookies_FullMethodName         = "/vkturn.appcontrol.v1.AppControl/GetVKCookies"
	AppControl_Provision_FullMethodName            = "/vkturn.appcontrol.v1.AppControl/Provision"
	AppControl_GetTelemetry_FullMethodName         = "/vkturn.appcontrol.v1.AppControl/GetTelemetry"
	AppControl_StreamTelemetry_FullMethodName      = "/vkturn.appcontrol.v1.AppControl/StreamTelemetry"
	AppControl_Configure_FullMethodName            = "/vkturn.appcontrol.v1.AppControl/Configure"
	AppControl_StreamEvents_FullMethodName         = "/vkturn.appcontrol.v1.AppControl/StreamEvents"
	AppControl_SubmitVKAccountCreds_FullMethodName = "/vkturn.appcontrol.v1.AppControl/SubmitVKAccountCreds"
	AppControl_PatchConfig_FullMethodName          = "/vkturn.appcontrol.v1.AppControl/PatchConfig"
	AppControl_StreamUnderlayIPs_FullMethodName    = "/vkturn.appcontrol.v1.AppControl/StreamUnderlayIPs"
)

// AppControlClient is the client API for AppControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppControlClient interface {
	SetVKCookies(ctx context.Context, in *SetVKCookiesRequest, opts ...grpc.CallOption) (*SetVKCookiesResponse, error)
	// GetVKCookies lets the app pull the current (possibly relay-rotated) session
	// over gRPC instead of reading a vk_cookies_update line off stdout, so cookies
	// never touch stdout / logcat.
	GetVKCookies(ctx context.Context, in *GetVKCookiesRequest, opts ...grpc.CallOption) (*GetVKCookiesResponse, error)
	Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error)
	// GetTelemetry returns the relay's live counters (connected TURN streams) once.
	GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*Telemetry, error)
	// StreamTelemetry pushes the connected-stream count the moment it changes, so the
	// app tracks connect progress event-driven (as fast as the old PROXY_EVENT stdout
	// scrape) instead of polling. The relay still prints the telemetry line for logs.
	StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Telemetry], error)
	// Configure delivers the relay runtime configuration the host app used to pass
	// as CLI flags. The relay launches with only the AppControl socket flags and
	// blocks until the app calls Configure, then boots its engine from these fields.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// StreamEvents pushes the relay's control events - connection-progress status,
	// capabilities, captcha prompts, VK account-auth drive - that formerly rode the
	// stdout PROXY_EVENT / PROXY_CAPS / CAPTCHA_ JSONL lines. The relay still prints
	// those lines, but now only for the log; control flows over this stream.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyEvent], error)
	// SubmitVKAccountCreds delivers the VK TURN credentials the host app intercepted
	// in its sign-in WebView (or a cancel) back to the relay, replacing the
	// vk_account_creds stdin line. Unlike stdin it also works on the root/kernel-WG
	// path, where the relay runs under su with no writable stdin.
	SubmitVKAccountCreds(ctx context.Context, in *VKAccountCredsRequest, opts ...grpc.CallOption) (*VKAccountCredsResponse, error)
	// PatchConfig live-applies a delta of runtime-mutable settings without a relay
	// restart. Only the present fields are patched. The relay migrates its TURN
	// worker fleet onto the new config snapshot gracefully (streams drain and recycle
	// one at a time, traffic is not interrupted) and reports per-field progress over
	// StreamEvents as PatchStatusEvent messages keyed by the request_id.
	PatchConfig(ctx context.Context, in *PatchConfigRequest, opts ...grpc.CallOption) (*PatchConfigResponse, error)
	// StreamUnderlayIPs pushes each remote IP the relay pins to the physical interface for
	// its own underlay (the VK TURN and peer servers it dials). On Windows the host app
	// installs a matching /32 bypass route via the physical gateway: per-socket interface
	// pinning alone leaves the tunnel's source address on the packet, which the upstream
	// router drops, so the underlay must be excluded from the full tunnel by route too. The
	// relay also logs each IP.
	StreamUnderlayIPs(ctx context.Context, in *StreamUnderlayIPsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnderlayIP], error)
}

type appControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAppControlClient(cc grpc.ClientConnInterface) AppControlClient {
	return &appControlClient{cc}
}

func (c *appControlClient) SetVKCookies(ctx context.Context, in *SetVKCookiesRequest, opts ...grpc.CallOption) (*SetVKCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVKCookiesResponse)
	err := c.cc.Invoke(ctx, AppControl_SetVKCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) GetVKCookies(ctx context.Context, in *GetVKCookiesRequest, opts ...grpc.CallOption) (*GetVKCookiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVKCookiesResponse)
	err := c.cc.Invoke(ctx, AppControl_GetVKCookies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) Provision(ctx context.Context, in *ProvisionRequest, opts ...grpc.CallOption) (*ProvisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionResponse)
	err := c.cc.Invoke(ctx, AppControl_Provision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*Telemetry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Telemetry)
	err := c.cc.Invoke(ctx, AppControl_GetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) StreamTelemetry(ctx context.Context, in *StreamTelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Telemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AppControl_ServiceDesc.Streams[0], AppControl_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTelemetryRequest, Telemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamTelemetryClient = grpc.ServerStreamingClient[Telemetry]

func (c *appControlClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, AppControl_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AppControl_ServiceDesc.Streams[1], AppControl_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, ProxyEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamEventsClient = grpc.ServerStreamingClient[ProxyEvent]

func (c *appControlClient) SubmitVKAccountCreds(ctx context.Context, in *VKAccountCredsRequest, opts ...grpc.CallOption) (*VKAccountCredsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VKAccountCredsResponse)
	err := c.cc.Invoke(ctx, AppControl_SubmitVKAccountCreds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) PatchConfig(ctx context.Context, in *PatchConfigRequest, opts ...grpc.CallOption) (*PatchConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchConfigResponse)
	err := c.cc.Invoke(ctx, AppControl_PatchConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appControlClient) StreamUnderlayIPs(ctx context.Context, in *StreamUnderlayIPsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UnderlayIP], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AppControl_ServiceDesc.Streams[2], AppControl_StreamUnderlayIPs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUnderlayIPsRequest, UnderlayIP]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamUnderlayIPsClient = grpc.ServerStreamingClient[UnderlayIP]

// AppControlServer is the server API for AppControl service.
// All implementations must embed UnimplementedAppControlServer
// for forward compatibility.
type AppControlServer interface {
	SetVKCookies(context.Context, *SetVKCookiesRequest) (*SetVKCookiesResponse, error)
	// GetVKCookies lets the app pull the current (possibly relay-rotated) session
	// over gRPC instead of reading a vk_cookies_update line off stdout, so cookies
	// never touch stdout / logcat.
	GetVKCookies(context.Context, *GetVKCookiesRequest) (*GetVKCookiesResponse, error)
	Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error)
	// GetTelemetry returns the relay's live counters (connected TURN streams) once.
	GetTelemetry(context.Context, *GetTelemetryRequest) (*Telemetry, error)
	// StreamTelemetry pushes the connected-stream count the moment it changes, so the
	// app tracks connect progress event-driven (as fast as the old PROXY_EVENT stdout
	// scrape) instead of polling. The relay still prints the telemetry line for logs.
	StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[Telemetry]) error
	// Configure delivers the relay runtime configuration the host app used to pass
	// as CLI flags. The relay launches with only the AppControl socket flags and
	// blocks until the app calls Configure, then boots its engine from these fields.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// StreamEvents pushes the relay's control events - connection-progress status,
	// capabilities, captcha prompts, VK account-auth drive - that formerly rode the
	// stdout PROXY_EVENT / PROXY_CAPS / CAPTCHA_ JSONL lines. The relay still prints
	// those lines, but now only for the log; control flows over this stream.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ProxyEvent]) error
	// SubmitVKAccountCreds delivers the VK TURN credentials the host app intercepted
	// in its sign-in WebView (or a cancel) back to the relay, replacing the
	// vk_account_creds stdin line. Unlike stdin it also works on the root/kernel-WG
	// path, where the relay runs under su with no writable stdin.
	SubmitVKAccountCreds(context.Context, *VKAccountCredsRequest) (*VKAccountCredsResponse, error)
	// PatchConfig live-applies a delta of runtime-mutable settings without a relay
	// restart. Only the present fields are patched. The relay migrates its TURN
	// worker fleet onto the new config snapshot gracefully (streams drain and recycle
	// one at a time, traffic is not interrupted) and reports per-field progress over
	// StreamEvents as PatchStatusEvent messages keyed by the request_id.
	PatchConfig(context.Context, *PatchConfigRequest) (*PatchConfigResponse, error)
	// StreamUnderlayIPs pushes each remote IP the relay pins to the physical interface for
	// its own underlay (the VK TURN and peer servers it dials). On Windows the host app
	// installs a matching /32 bypass route via the physical gateway: per-socket interface
	// pinning alone leaves the tunnel's source address on the packet, which the upstream
	// router drops, so the underlay must be excluded from the full tunnel by route too. The
	// relay also logs each IP.
	StreamUnderlayIPs(*StreamUnderlayIPsRequest, grpc.ServerStreamingServer[UnderlayIP]) error
	mustEmbedUnimplementedAppControlServer()
}

// UnimplementedAppControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppControlServer struct{}

func (UnimplementedAppControlServer) SetVKCookies(context.Context, *SetVKCookiesRequest) (*SetVKCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVKCookies not implemented")
}
func (UnimplementedAppControlServer) GetVKCookies(context.Context, *GetVKCookiesRequest) (*GetVKCookiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVKCookies not implemented")
}
func (UnimplementedAppControlServer) Provision(context.Context, *ProvisionRequest) (*ProvisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Provision not implemented")
}
func (UnimplementedAppControlServer) GetTelemetry(context.Context, *GetTelemetryRequest) (*Telemetry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTelemetry not implemented")
}
func (UnimplementedAppControlServer) StreamTelemetry(*StreamTelemetryRequest, grpc.ServerStreamingServer[Telemetry]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedAppControlServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedAppControlServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ProxyEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAppControlServer) SubmitVKAccountCreds(context.Context, *VKAccountCredsRequest) (*VKAccountCredsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitVKAccountCreds not implemented")
}
func (UnimplementedAppControlServer) PatchConfig(context.Context, *PatchConfigRequest) (*PatchConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchConfig not implemented")
}
func (UnimplementedAppControlServer) StreamUnderlayIPs(*StreamUnderlayIPsRequest, grpc.ServerStreamingServer[UnderlayIP]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUnderlayIPs not implemented")
}
func (UnimplementedAppControlServer) mustEmbedUnimplementedAppControlServer() {}
func (UnimplementedAppControlServer) testEmbeddedByValue()                    {}

// UnsafeAppControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppControlServer will
// result in compilation errors.
type UnsafeAppControlServer interface {
	mustEmbedUnimplementedAppControlServer()
}

func RegisterAppControlServer(s grpc.ServiceRegistrar, srv AppControlServer) {
	// If the following call pancis, it indicates UnimplementedAppControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppControl_ServiceDesc, srv)
}

func _AppControl_SetVKCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVKCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).SetVKCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_SetVKCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).SetVKCookies(ctx, req.(*SetVKCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_GetVKCookies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVKCookiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).GetVKCookies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_GetVKCookies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).GetVKCookies(ctx, req.(*GetVKCookiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_Provision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).Provision(ctx, req.(*ProvisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_GetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).GetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_GetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).GetTelemetry(ctx, req.(*GetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppControlServer).StreamTelemetry(m, &grpc.GenericServerStream[StreamTelemetryRequest, Telemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamTelemetryServer = grpc.ServerStreamingServer[Telemetry]

func _AppControl_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppControlServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, ProxyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamEventsServer = grpc.ServerStreamingServer[ProxyEvent]

func _AppControl_SubmitVKAccountCreds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VKAccountCredsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).SubmitVKAccountCreds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_SubmitVKAccountCreds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).SubmitVKAccountCreds(ctx, req.(*VKAccountCredsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_PatchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppControlServer).PatchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppControl_PatchConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppControlServer).PatchConfig(ctx, req.(*PatchConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppControl_StreamUnderlayIPs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamUnderlayIPsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppControlServer).StreamUnderlayIPs(m, &grpc.GenericServerStream[StreamUnderlayIPsRequest, UnderlayIP]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppControl_StreamUnderlayIPsServer = grpc.ServerStreamingServer[UnderlayIP]

// AppControl_ServiceDesc is the grpc.ServiceDesc for AppControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vkturn.appcontrol.v1.AppControl",
	HandlerType: (*AppControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVKCookies",
			Handler:    _AppControl_SetVKCookies_Handler,
		},
		{
			MethodName: "GetVKCookies",
			Handler:    _AppControl_GetVKCookies_Handler,
		},
		{
			MethodName: "Provision",
			Handler:    _AppControl_Provision_Handler,
		},
		{
			MethodName: "GetTelemetry",
			Handler:    _AppControl_GetTelemetry_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _AppControl_Configure_Handler,
		},
		{
			MethodName: "SubmitVKAccountCreds",
			Handler:    _AppControl_SubmitVKAccountCreds_Handler,
		},
		{
			MethodName: "PatchConfig",
			Handler:    _AppControl_PatchConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _AppControl_StreamTelemetry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _AppControl_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamUnderlayIPs",
			Handler:       _AppControl_StreamUnderlayIPs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/appcontrol.proto",
}
