// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/provisioning.proto

// Package and service names mirror the panel's provisioning.proto exactly so the
// generated method paths line up; only go_package differs. This is the node
// (client) side: during app self-enroll the node calls the panel to verify the
// client token and obtain (creating on first use) the client's WireGuard config.

package provisioningpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Provisioning_ResolveClientConfig_FullMethodName = "/wingsv.provisioning.v1.Provisioning/ResolveClientConfig"
	Provisioning_GetClientUsage_FullMethodName      = "/wingsv.provisioning.v1.Provisioning/GetClientUsage"
)

// ProvisioningClient is the client API for Provisioning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvisioningClient interface {
	ResolveClientConfig(ctx context.Context, in *ResolveClientConfigRequest, opts ...grpc.CallOption) (*ResolveClientConfigResponse, error)
	// GetClientUsage returns the traffic-limit usage of the capped or disabled
	// managed clients that hold a wg peer on the calling node. The relay polls it
	// and surfaces used/remaining to the app (e.g. in its DTLS heartbeat) and can
	// also enforce a hard cutoff. Clients with no cap and not disabled are omitted.
	GetClientUsage(ctx context.Context, in *GetClientUsageRequest, opts ...grpc.CallOption) (*GetClientUsageResponse, error)
}

type provisioningClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisioningClient(cc grpc.ClientConnInterface) ProvisioningClient {
	return &provisioningClient{cc}
}

func (c *provisioningClient) ResolveClientConfig(ctx context.Context, in *ResolveClientConfigRequest, opts ...grpc.CallOption) (*ResolveClientConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveClientConfigResponse)
	err := c.cc.Invoke(ctx, Provisioning_ResolveClientConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisioningClient) GetClientUsage(ctx context.Context, in *GetClientUsageRequest, opts ...grpc.CallOption) (*GetClientUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientUsageResponse)
	err := c.cc.Invoke(ctx, Provisioning_GetClientUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisioningServer is the server API for Provisioning service.
// All implementations must embed UnimplementedProvisioningServer
// for forward compatibility.
type ProvisioningServer interface {
	ResolveClientConfig(context.Context, *ResolveClientConfigRequest) (*ResolveClientConfigResponse, error)
	// GetClientUsage returns the traffic-limit usage of the capped or disabled
	// managed clients that hold a wg peer on the calling node. The relay polls it
	// and surfaces used/remaining to the app (e.g. in its DTLS heartbeat) and can
	// also enforce a hard cutoff. Clients with no cap and not disabled are omitted.
	GetClientUsage(context.Context, *GetClientUsageRequest) (*GetClientUsageResponse, error)
	mustEmbedUnimplementedProvisioningServer()
}

// UnimplementedProvisioningServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisioningServer struct{}

func (UnimplementedProvisioningServer) ResolveClientConfig(context.Context, *ResolveClientConfigRequest) (*ResolveClientConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveClientConfig not implemented")
}
func (UnimplementedProvisioningServer) GetClientUsage(context.Context, *GetClientUsageRequest) (*GetClientUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientUsage not implemented")
}
func (UnimplementedProvisioningServer) mustEmbedUnimplementedProvisioningServer() {}
func (UnimplementedProvisioningServer) testEmbeddedByValue()                      {}

// UnsafeProvisioningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisioningServer will
// result in compilation errors.
type UnsafeProvisioningServer interface {
	mustEmbedUnimplementedProvisioningServer()
}

func RegisterProvisioningServer(s grpc.ServiceRegistrar, srv ProvisioningServer) {
	// If the following call pancis, it indicates UnimplementedProvisioningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provisioning_ServiceDesc, srv)
}

func _Provisioning_ResolveClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisioningServer).ResolveClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provisioning_ResolveClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisioningServer).ResolveClientConfig(ctx, req.(*ResolveClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provisioning_GetClientUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisioningServer).GetClientUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provisioning_GetClientUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisioningServer).GetClientUsage(ctx, req.(*GetClientUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Provisioning_ServiceDesc is the grpc.ServiceDesc for Provisioning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provisioning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wingsv.provisioning.v1.Provisioning",
	HandlerType: (*ProvisioningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveClientConfig",
			Handler:    _Provisioning_ResolveClientConfig_Handler,
		},
		{
			MethodName: "GetClientUsage",
			Handler:    _Provisioning_GetClientUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/provisioning.proto",
}
