// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/provisioning.proto

// Package and service names mirror the panel's provisioning.proto exactly so the
// generated method paths line up; only go_package differs. This is the node
// (client) side: during app self-enroll the node calls the panel to verify the
// client token and obtain (creating on first use) the client's WireGuard config.

package provisioningpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveClientConfigRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Token    []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hwid     string                 `protobuf:"bytes,3,opt,name=hwid,proto3" json:"hwid,omitempty"`
	NodeId   string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// When set, this node reports a wg peer it just minted locally for the client
	// (own-wg provision-locally path); the panel records it instead of dialing back
	// this node's management API. Empty on the initial resolve.
	WgPublicKey       string `protobuf:"bytes,5,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"`
	WgPrivateKey      string `protobuf:"bytes,6,opt,name=wg_private_key,json=wgPrivateKey,proto3" json:"wg_private_key,omitempty"`
	WgAllowedIps      string `protobuf:"bytes,7,opt,name=wg_allowed_ips,json=wgAllowedIps,proto3" json:"wg_allowed_ips,omitempty"`
	WgServerPublicKey string `protobuf:"bytes,8,opt,name=wg_server_public_key,json=wgServerPublicKey,proto3" json:"wg_server_public_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveClientConfigRequest) Reset() {
	*x = ResolveClientConfigRequest{}
	mi := &file_proto_provisioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveClientConfigRequest) ProtoMessage() {}

func (x *ResolveClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveClientConfigRequest.ProtoReflect.Descriptor instead.
func (*ResolveClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveClientConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ResolveClientConfigRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetWgPrivateKey() string {
	if x != nil {
		return x.WgPrivateKey
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetWgAllowedIps() string {
	if x != nil {
		return x.WgAllowedIps
	}
	return ""
}

func (x *ResolveClientConfigRequest) GetWgServerPublicKey() string {
	if x != nil {
		return x.WgServerPublicKey
	}
	return ""
}

type ResolveClientConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Wg    *WireguardConfig       `protobuf:"bytes,1,opt,name=wg,proto3" json:"wg,omitempty"`
	// provision_locally: mint the peer on this node's own wg interface and re-call
	// ResolveClientConfig with the wg_* fields to record it, instead of the panel
	// dialing this node back (a re-entrant call that breaks during provision).
	ProvisionLocally bool `protobuf:"varint,2,opt,name=provision_locally,json=provisionLocally,proto3" json:"provision_locally,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveClientConfigResponse) Reset() {
	*x = ResolveClientConfigResponse{}
	mi := &file_proto_provisioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveClientConfigResponse) ProtoMessage() {}

func (x *ResolveClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveClientConfigResponse.ProtoReflect.Descriptor instead.
func (*ResolveClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveClientConfigResponse) GetWg() *WireguardConfig {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *ResolveClientConfigResponse) GetProvisionLocally() bool {
	if x != nil {
		return x.ProvisionLocally
	}
	return false
}

type GetClientUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientUsageRequest) Reset() {
	*x = GetClientUsageRequest{}
	mi := &file_proto_provisioning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientUsageRequest) ProtoMessage() {}

func (x *GetClientUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientUsageRequest.ProtoReflect.Descriptor instead.
func (*GetClientUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientUsageRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetClientUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         []*ClientUsage         `protobuf:"bytes,1,rep,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientUsageResponse) Reset() {
	*x = GetClientUsageResponse{}
	mi := &file_proto_provisioning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientUsageResponse) ProtoMessage() {}

func (x *GetClientUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientUsageResponse.ProtoReflect.Descriptor instead.
func (*GetClientUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientUsageResponse) GetUsage() []*ClientUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// ClientUsage is one managed client's traffic-limit state on the calling node,
// keyed by its wg peer public key so the relay can match it to a live session.
type ClientUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PublicKey      string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	LimitBytes     uint64                 `protobuf:"varint,3,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	RemainingBytes uint64                 `protobuf:"varint,5,opt,name=remaining_bytes,json=remainingBytes,proto3" json:"remaining_bytes,omitempty"`
	Disabled       bool                   `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientUsage) Reset() {
	*x = ClientUsage{}
	mi := &file_proto_provisioning_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUsage) ProtoMessage() {}

func (x *ClientUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUsage.ProtoReflect.Descriptor instead.
func (*ClientUsage) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{4}
}

func (x *ClientUsage) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ClientUsage) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientUsage) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *ClientUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *ClientUsage) GetRemainingBytes() uint64 {
	if x != nil {
		return x.RemainingBytes
	}
	return 0
}

func (x *ClientUsage) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type WireguardConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey      string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey       string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,4,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	AllowedIps      string                 `protobuf:"bytes,5,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Mtu             uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WireguardConfig) Reset() {
	*x = WireguardConfig{}
	mi := &file_proto_provisioning_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardConfig) ProtoMessage() {}

func (x *WireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_provisioning_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardConfig.ProtoReflect.Descriptor instead.
func (*WireguardConfig) Descriptor() ([]byte, []int) {
	return file_proto_provisioning_proto_rawDescGZIP(), []int{5}
}

func (x *WireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireguardConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireguardConfig) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *WireguardConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

var File_proto_provisioning_proto protoreflect.FileDescriptor

const file_proto_provisioning_proto_rawDesc = "" +
	"\n" +
	"\x18proto/provisioning.proto\x12\x16wingsv.provisioning.v1\"\x9d\x02\n" +
	"\x1aResolveClientConfigRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x12\n" +
	"\x04hwid\x18\x03 \x01(\tR\x04hwid\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\"\n" +
	"\rwg_public_key\x18\x05 \x01(\tR\vwgPublicKey\x12$\n" +
	"\x0ewg_private_key\x18\x06 \x01(\tR\fwgPrivateKey\x12$\n" +
	"\x0ewg_allowed_ips\x18\a \x01(\tR\fwgAllowedIps\x12/\n" +
	"\x14wg_server_public_key\x18\b \x01(\tR\x11wgServerPublicKey\"\x83\x01\n" +
	"\x1bResolveClientConfigResponse\x127\n" +
	"\x02wg\x18\x01 \x01(\v2'.wingsv.provisioning.v1.WireguardConfigR\x02wg\x12+\n" +
	"\x11provision_locally\x18\x02 \x01(\bR\x10provisionLocally\"0\n" +
	"\x15GetClientUsageRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"S\n" +
	"\x16GetClientUsageResponse\x129\n" +
	"\x05usage\x18\x01 \x03(\v2#.wingsv.provisioning.v1.ClientUsageR\x05usage\"\xce\x01\n" +
	"\vClientUsage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vlimit_bytes\x18\x03 \x01(\x04R\n" +
	"limitBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12'\n" +
	"\x0fremaining_bytes\x18\x05 \x01(\x04R\x0eremainingBytes\x12\x1a\n" +
	"\bdisabled\x18\x06 \x01(\bR\bdisabled\"\xca\x01\n" +
	"\x0fWireguardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12*\n" +
	"\x11server_public_key\x18\x04 \x01(\tR\x0fserverPublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x01(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu2\xff\x01\n" +
	"\fProvisioning\x12~\n" +
	"\x13ResolveClientConfig\x122.wingsv.provisioning.v1.ResolveClientConfigRequest\x1a3.wingsv.provisioning.v1.ResolveClientConfigResponse\x12o\n" +
	"\x0eGetClientUsage\x12-.wingsv.provisioning.v1.GetClientUsageRequest\x1a..wingsv.provisioning.v1.GetClientUsageResponseBAZ?github.com/cacggghp/vk-turn-proxy/provisioningpb;provisioningpbb\x06proto3"

var (
	file_proto_provisioning_proto_rawDescOnce sync.Once
	file_proto_provisioning_proto_rawDescData []byte
)

func file_proto_provisioning_proto_rawDescGZIP() []byte {
	file_proto_provisioning_proto_rawDescOnce.Do(func() {
		file_proto_provisioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_provisioning_proto_rawDesc), len(file_proto_provisioning_proto_rawDesc)))
	})
	return file_proto_provisioning_proto_rawDescData
}

var file_proto_provisioning_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_provisioning_proto_goTypes = []any{
	(*ResolveClientConfigRequest)(nil),  // 0: wingsv.provisioning.v1.ResolveClientConfigRequest
	(*ResolveClientConfigResponse)(nil), // 1: wingsv.provisioning.v1.ResolveClientConfigResponse
	(*GetClientUsageRequest)(nil),       // 2: wingsv.provisioning.v1.GetClientUsageRequest
	(*GetClientUsageResponse)(nil),      // 3: wingsv.provisioning.v1.GetClientUsageResponse
	(*ClientUsage)(nil),                 // 4: wingsv.provisioning.v1.ClientUsage
	(*WireguardConfig)(nil),             // 5: wingsv.provisioning.v1.WireguardConfig
}
var file_proto_provisioning_proto_depIdxs = []int32{
	5, // 0: wingsv.provisioning.v1.ResolveClientConfigResponse.wg:type_name -> wingsv.provisioning.v1.WireguardConfig
	4, // 1: wingsv.provisioning.v1.GetClientUsageResponse.usage:type_name -> wingsv.provisioning.v1.ClientUsage
	0, // 2: wingsv.provisioning.v1.Provisioning.ResolveClientConfig:input_type -> wingsv.provisioning.v1.ResolveClientConfigRequest
	2, // 3: wingsv.provisioning.v1.Provisioning.GetClientUsage:input_type -> wingsv.provisioning.v1.GetClientUsageRequest
	1, // 4: wingsv.provisioning.v1.Provisioning.ResolveClientConfig:output_type -> wingsv.provisioning.v1.ResolveClientConfigResponse
	3, // 5: wingsv.provisioning.v1.Provisioning.GetClientUsage:output_type -> wingsv.provisioning.v1.GetClientUsageResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_provisioning_proto_init() }
func file_proto_provisioning_proto_init() {
	if File_proto_provisioning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_provisioning_proto_rawDesc), len(file_proto_provisioning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_provisioning_proto_goTypes,
		DependencyIndexes: file_proto_provisioning_proto_depIdxs,
		MessageInfos:      file_proto_provisioning_proto_msgTypes,
	}.Build()
	File_proto_provisioning_proto = out.File
	file_proto_provisioning_proto_goTypes = nil
	file_proto_provisioning_proto_depIdxs = nil
}
