// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/session.proto

package sessionproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientHelloType int32

const (
	ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED   ClientHelloType = 0
	ClientHelloType_CLIENT_HELLO_TYPE_PROBE         ClientHelloType = 1
	ClientHelloType_CLIENT_HELLO_TYPE_SESSION       ClientHelloType = 2
	ClientHelloType_CLIENT_HELLO_TYPE_ROOM_EXCHANGE ClientHelloType = 3
	ClientHelloType_CLIENT_HELLO_TYPE_PROVISION     ClientHelloType = 4
)

// Enum value maps for ClientHelloType.
var (
	ClientHelloType_name = map[int32]string{
		0: "CLIENT_HELLO_TYPE_UNSPECIFIED",
		1: "CLIENT_HELLO_TYPE_PROBE",
		2: "CLIENT_HELLO_TYPE_SESSION",
		3: "CLIENT_HELLO_TYPE_ROOM_EXCHANGE",
		4: "CLIENT_HELLO_TYPE_PROVISION",
	}
	ClientHelloType_value = map[string]int32{
		"CLIENT_HELLO_TYPE_UNSPECIFIED":   0,
		"CLIENT_HELLO_TYPE_PROBE":         1,
		"CLIENT_HELLO_TYPE_SESSION":       2,
		"CLIENT_HELLO_TYPE_ROOM_EXCHANGE": 3,
		"CLIENT_HELLO_TYPE_PROVISION":     4,
	}
)

func (x ClientHelloType) Enum() *ClientHelloType {
	p := new(ClientHelloType)
	*p = x
	return p
}

func (x ClientHelloType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientHelloType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[0].Descriptor()
}

func (ClientHelloType) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[0]
}

func (x ClientHelloType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientHelloType.Descriptor instead.
func (ClientHelloType) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

type TransportMode int32

const (
	TransportMode_TRANSPORT_MODE_UNSPECIFIED TransportMode = 0
	TransportMode_TRANSPORT_MODE_DATAGRAM    TransportMode = 1
	TransportMode_TRANSPORT_MODE_TCP         TransportMode = 2
)

// Enum value maps for TransportMode.
var (
	TransportMode_name = map[int32]string{
		0: "TRANSPORT_MODE_UNSPECIFIED",
		1: "TRANSPORT_MODE_DATAGRAM",
		2: "TRANSPORT_MODE_TCP",
	}
	TransportMode_value = map[string]int32{
		"TRANSPORT_MODE_UNSPECIFIED": 0,
		"TRANSPORT_MODE_DATAGRAM":    1,
		"TRANSPORT_MODE_TCP":         2,
	}
)

func (x TransportMode) Enum() *TransportMode {
	p := new(TransportMode)
	*p = x
	return p
}

func (x TransportMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[1].Descriptor()
}

func (TransportMode) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[1]
}

func (x TransportMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportMode.Descriptor instead.
func (TransportMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

type TcpTransportFlavor int32

const (
	TcpTransportFlavor_TCP_TRANSPORT_FLAVOR_UNSPECIFIED     TcpTransportFlavor = 0
	TcpTransportFlavor_TCP_TRANSPORT_FLAVOR_LEGACY_KCP_SMUX TcpTransportFlavor = 1
	TcpTransportFlavor_TCP_TRANSPORT_FLAVOR_DIRECT_SMUX     TcpTransportFlavor = 2
)

// Enum value maps for TcpTransportFlavor.
var (
	TcpTransportFlavor_name = map[int32]string{
		0: "TCP_TRANSPORT_FLAVOR_UNSPECIFIED",
		1: "TCP_TRANSPORT_FLAVOR_LEGACY_KCP_SMUX",
		2: "TCP_TRANSPORT_FLAVOR_DIRECT_SMUX",
	}
	TcpTransportFlavor_value = map[string]int32{
		"TCP_TRANSPORT_FLAVOR_UNSPECIFIED":     0,
		"TCP_TRANSPORT_FLAVOR_LEGACY_KCP_SMUX": 1,
		"TCP_TRANSPORT_FLAVOR_DIRECT_SMUX":     2,
	}
)

func (x TcpTransportFlavor) Enum() *TcpTransportFlavor {
	p := new(TcpTransportFlavor)
	*p = x
	return p
}

func (x TcpTransportFlavor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TcpTransportFlavor) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[2].Descriptor()
}

func (TcpTransportFlavor) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[2]
}

func (x TcpTransportFlavor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TcpTransportFlavor.Descriptor instead.
func (TcpTransportFlavor) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{2}
}

type WrapCipher int32

const (
	WrapCipher_WRAP_CIPHER_UNSPECIFIED WrapCipher = 0
	WrapCipher_WRAP_CIPHER_NONE        WrapCipher = 1
	// SRTP-mimicry AEAD. The wire packet is [12B RTP header | 12B nonce |
	// AEAD ciphertext | 16B tag]; the RTP header makes the datagram look
	// like opus voice traffic so VK TURN's content filter forwards it on
	// the fast path.
	WrapCipher_WRAP_CIPHER_SRTP_AES_256_GCM       WrapCipher = 2
	WrapCipher_WRAP_CIPHER_SRTP_CHACHA20_POLY1305 WrapCipher = 3
)

// Enum value maps for WrapCipher.
var (
	WrapCipher_name = map[int32]string{
		0: "WRAP_CIPHER_UNSPECIFIED",
		1: "WRAP_CIPHER_NONE",
		2: "WRAP_CIPHER_SRTP_AES_256_GCM",
		3: "WRAP_CIPHER_SRTP_CHACHA20_POLY1305",
	}
	WrapCipher_value = map[string]int32{
		"WRAP_CIPHER_UNSPECIFIED":            0,
		"WRAP_CIPHER_NONE":                   1,
		"WRAP_CIPHER_SRTP_AES_256_GCM":       2,
		"WRAP_CIPHER_SRTP_CHACHA20_POLY1305": 3,
	}
)

func (x WrapCipher) Enum() *WrapCipher {
	p := new(WrapCipher)
	*p = x
	return p
}

func (x WrapCipher) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WrapCipher) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[3].Descriptor()
}

func (WrapCipher) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[3]
}

func (x WrapCipher) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WrapCipher.Descriptor instead.
func (WrapCipher) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{3}
}

type RoomProvider int32

const (
	RoomProvider_ROOM_PROVIDER_UNSPECIFIED RoomProvider = 0
	RoomProvider_ROOM_PROVIDER_WB_STREAM   RoomProvider = 1
)

// Enum value maps for RoomProvider.
var (
	RoomProvider_name = map[int32]string{
		0: "ROOM_PROVIDER_UNSPECIFIED",
		1: "ROOM_PROVIDER_WB_STREAM",
	}
	RoomProvider_value = map[string]int32{
		"ROOM_PROVIDER_UNSPECIFIED": 0,
		"ROOM_PROVIDER_WB_STREAM":   1,
	}
)

func (x RoomProvider) Enum() *RoomProvider {
	p := new(RoomProvider)
	*p = x
	return p
}

func (x RoomProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_session_proto_enumTypes[4].Descriptor()
}

func (RoomProvider) Type() protoreflect.EnumType {
	return &file_proto_session_proto_enumTypes[4]
}

func (x RoomProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomProvider.Descriptor instead.
func (RoomProvider) EnumDescriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{4}
}

type ClientHello struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                ClientHelloType        `protobuf:"varint,2,opt,name=type,proto3,enum=sessionproto.ClientHelloType" json:"type,omitempty"`
	SessionId           []byte                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId            uint32                 `protobuf:"varint,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	RequestedTransport  TransportMode          `protobuf:"varint,5,opt,name=requested_transport,json=requestedTransport,proto3,enum=sessionproto.TransportMode" json:"requested_transport,omitempty"`
	SupportedTransports []TransportMode        `protobuf:"varint,6,rep,packed,name=supported_transports,json=supportedTransports,proto3,enum=sessionproto.TransportMode" json:"supported_transports,omitempty"`
	SupportedTcpFlavors []TcpTransportFlavor   `protobuf:"varint,7,rep,packed,name=supported_tcp_flavors,json=supportedTcpFlavors,proto3,enum=sessionproto.TcpTransportFlavor" json:"supported_tcp_flavors,omitempty"`
	PreferredTcpFlavor  TcpTransportFlavor     `protobuf:"varint,8,opt,name=preferred_tcp_flavor,json=preferredTcpFlavor,proto3,enum=sessionproto.TcpTransportFlavor" json:"preferred_tcp_flavor,omitempty"`
	RoomExchange        *RoomDataExchange      `protobuf:"bytes,9,opt,name=room_exchange,json=roomExchange,proto3" json:"room_exchange,omitempty"`
	// WRAP per-packet obfuscation negotiation. Order in supported_wrap_ciphers
	// expresses client preference (most-preferred first).
	SupportedWrapCiphers []WrapCipher `protobuf:"varint,10,rep,packed,name=supported_wrap_ciphers,json=supportedWrapCiphers,proto3,enum=sessionproto.WrapCipher" json:"supported_wrap_ciphers,omitempty"`
	// Optional client-proposed shared key (32 bytes for AES-256-CTR/ChaCha20).
	// Server may accept or fall back to its preset key based on configuration.
	WrapKeyProposal []byte `protobuf:"bytes,11,opt,name=wrap_key_proposal,json=wrapKeyProposal,proto3" json:"wrap_key_proposal,omitempty"`
	// Set on CLIENT_HELLO_TYPE_PROVISION: the app asks the node to mint (or return)
	// its WireGuard config. The node forwards client_id + token to the panel over
	// gRPC for verification; it never mints a config on its own.
	Provision *ProvisionRequest `protobuf:"bytes,12,opt,name=provision,proto3" json:"provision,omitempty"`
	// Managed clients announce their panel client id on every SESSION hello (it is
	// not a secret, unlike the provision token) so the node can attribute the
	// session to a client and report that client's traffic-limit usage back in the
	// heartbeat.
	ClientId      string `protobuf:"bytes,13,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientHello) GetType() ClientHelloType {
	if x != nil {
		return x.Type
	}
	return ClientHelloType_CLIENT_HELLO_TYPE_UNSPECIFIED
}

func (x *ClientHello) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ClientHello) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *ClientHello) GetRequestedTransport() TransportMode {
	if x != nil {
		return x.RequestedTransport
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *ClientHello) GetSupportedTransports() []TransportMode {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

func (x *ClientHello) GetSupportedTcpFlavors() []TcpTransportFlavor {
	if x != nil {
		return x.SupportedTcpFlavors
	}
	return nil
}

func (x *ClientHello) GetPreferredTcpFlavor() TcpTransportFlavor {
	if x != nil {
		return x.PreferredTcpFlavor
	}
	return TcpTransportFlavor_TCP_TRANSPORT_FLAVOR_UNSPECIFIED
}

func (x *ClientHello) GetRoomExchange() *RoomDataExchange {
	if x != nil {
		return x.RoomExchange
	}
	return nil
}

func (x *ClientHello) GetSupportedWrapCiphers() []WrapCipher {
	if x != nil {
		return x.SupportedWrapCiphers
	}
	return nil
}

func (x *ClientHello) GetWrapKeyProposal() []byte {
	if x != nil {
		return x.WrapKeyProposal
	}
	return nil
}

func (x *ClientHello) GetProvision() *ProvisionRequest {
	if x != nil {
		return x.Provision
	}
	return nil
}

func (x *ClientHello) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ProvisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Hwid          string                 `protobuf:"bytes,3,opt,name=hwid,proto3" json:"hwid,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_proto_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProvisionRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ProvisionRequest) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *ProvisionRequest) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wg            *WireguardConfig       `protobuf:"bytes,1,opt,name=wg,proto3" json:"wg,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_proto_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionResponse) GetWg() *WireguardConfig {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *ProvisionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WireguardConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey      string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey       string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	ServerPublicKey string                 `protobuf:"bytes,4,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	AllowedIps      string                 `protobuf:"bytes,5,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Mtu             uint32                 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WireguardConfig) Reset() {
	*x = WireguardConfig{}
	mi := &file_proto_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardConfig) ProtoMessage() {}

func (x *WireguardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardConfig.ProtoReflect.Descriptor instead.
func (*WireguardConfig) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{3}
}

func (x *WireguardConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WireguardConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WireguardConfig) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *WireguardConfig) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *WireguardConfig) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type RoomDataExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      RoomProvider           `protobuf:"varint,1,opt,name=provider,proto3,enum=sessionproto.RoomProvider" json:"provider,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	E2EEnabled    bool                   `protobuf:"varint,4,opt,name=e2e_enabled,json=e2eEnabled,proto3" json:"e2e_enabled,omitempty"`
	E2ESecret     []byte                 `protobuf:"bytes,5,opt,name=e2e_secret,json=e2eSecret,proto3" json:"e2e_secret,omitempty"`
	RoomIds       []string               `protobuf:"bytes,6,rep,name=room_ids,json=roomIds,proto3" json:"room_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDataExchange) Reset() {
	*x = RoomDataExchange{}
	mi := &file_proto_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDataExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDataExchange) ProtoMessage() {}

func (x *RoomDataExchange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDataExchange.ProtoReflect.Descriptor instead.
func (*RoomDataExchange) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{4}
}

func (x *RoomDataExchange) GetProvider() RoomProvider {
	if x != nil {
		return x.Provider
	}
	return RoomProvider_ROOM_PROVIDER_UNSPECIFIED
}

func (x *RoomDataExchange) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomDataExchange) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RoomDataExchange) GetE2EEnabled() bool {
	if x != nil {
		return x.E2EEnabled
	}
	return false
}

func (x *RoomDataExchange) GetE2ESecret() []byte {
	if x != nil {
		return x.E2ESecret
	}
	return nil
}

func (x *RoomDataExchange) GetRoomIds() []string {
	if x != nil {
		return x.RoomIds
	}
	return nil
}

type RoomDataAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDataAck) Reset() {
	*x = RoomDataAck{}
	mi := &file_proto_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDataAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDataAck) ProtoMessage() {}

func (x *RoomDataAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDataAck.ProtoReflect.Descriptor instead.
func (*RoomDataAck) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{5}
}

func (x *RoomDataAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RoomDataAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ServerHello struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Version                   uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MuSupported               bool                   `protobuf:"varint,2,opt,name=mu_supported,json=muSupported,proto3" json:"mu_supported,omitempty"`
	Error                     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ControlHeartbeatSupported bool                   `protobuf:"varint,4,opt,name=control_heartbeat_supported,json=controlHeartbeatSupported,proto3" json:"control_heartbeat_supported,omitempty"`
	SelectedTransport         TransportMode          `protobuf:"varint,5,opt,name=selected_transport,json=selectedTransport,proto3,enum=sessionproto.TransportMode" json:"selected_transport,omitempty"`
	SupportedTransports       []TransportMode        `protobuf:"varint,6,rep,packed,name=supported_transports,json=supportedTransports,proto3,enum=sessionproto.TransportMode" json:"supported_transports,omitempty"`
	SupportedTcpFlavors       []TcpTransportFlavor   `protobuf:"varint,7,rep,packed,name=supported_tcp_flavors,json=supportedTcpFlavors,proto3,enum=sessionproto.TcpTransportFlavor" json:"supported_tcp_flavors,omitempty"`
	SelectedTcpFlavor         TcpTransportFlavor     `protobuf:"varint,8,opt,name=selected_tcp_flavor,json=selectedTcpFlavor,proto3,enum=sessionproto.TcpTransportFlavor" json:"selected_tcp_flavor,omitempty"`
	// Final WRAP cipher chosen by the server.
	//
	//	WRAP_CIPHER_UNSPECIFIED / WRAP_CIPHER_NONE → stay on raw datagrams.
	SelectedWrapCipher WrapCipher `protobuf:"varint,9,opt,name=selected_wrap_cipher,json=selectedWrapCipher,proto3,enum=sessionproto.WrapCipher" json:"selected_wrap_cipher,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{6}
}

func (x *ServerHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerHello) GetMuSupported() bool {
	if x != nil {
		return x.MuSupported
	}
	return false
}

func (x *ServerHello) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ServerHello) GetControlHeartbeatSupported() bool {
	if x != nil {
		return x.ControlHeartbeatSupported
	}
	return false
}

func (x *ServerHello) GetSelectedTransport() TransportMode {
	if x != nil {
		return x.SelectedTransport
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *ServerHello) GetSupportedTransports() []TransportMode {
	if x != nil {
		return x.SupportedTransports
	}
	return nil
}

func (x *ServerHello) GetSupportedTcpFlavors() []TcpTransportFlavor {
	if x != nil {
		return x.SupportedTcpFlavors
	}
	return nil
}

func (x *ServerHello) GetSelectedTcpFlavor() TcpTransportFlavor {
	if x != nil {
		return x.SelectedTcpFlavor
	}
	return TcpTransportFlavor_TCP_TRANSPORT_FLAVOR_UNSPECIFIED
}

func (x *ServerHello) GetSelectedWrapCipher() WrapCipher {
	if x != nil {
		return x.SelectedWrapCipher
	}
	return WrapCipher_WRAP_CIPHER_UNSPECIFIED
}

type Heartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	WallClockMs      int64                  `protobuf:"varint,2,opt,name=wall_clock_ms,json=wallClockMs,proto3" json:"wall_clock_ms,omitempty"`
	ActiveStreams    uint32                 `protobuf:"varint,3,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	Online           bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	ProtoFingerprint string                 `protobuf:"bytes,5,opt,name=proto_fingerprint,json=protoFingerprint,proto3" json:"proto_fingerprint,omitempty"`
	SessionMode      string                 `protobuf:"bytes,6,opt,name=session_mode,json=sessionMode,proto3" json:"session_mode,omitempty"`
	ControlPath      string                 `protobuf:"bytes,7,opt,name=control_path,json=controlPath,proto3" json:"control_path,omitempty"`
	Provider         string                 `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	Transport        TransportMode          `protobuf:"varint,9,opt,name=transport,proto3,enum=sessionproto.TransportMode" json:"transport,omitempty"`
	// Managed-client traffic-limit state the node fetched from the panel and echoes
	// to the app so it can show used/remaining. traffic_present distinguishes "the
	// node has usage for this client" from an absent/zero reading; limit 0 = no cap.
	TrafficPresent        bool   `protobuf:"varint,10,opt,name=traffic_present,json=trafficPresent,proto3" json:"traffic_present,omitempty"`
	TrafficLimitBytes     uint64 `protobuf:"varint,11,opt,name=traffic_limit_bytes,json=trafficLimitBytes,proto3" json:"traffic_limit_bytes,omitempty"`
	TrafficUsedBytes      uint64 `protobuf:"varint,12,opt,name=traffic_used_bytes,json=trafficUsedBytes,proto3" json:"traffic_used_bytes,omitempty"`
	TrafficRemainingBytes uint64 `protobuf:"varint,13,opt,name=traffic_remaining_bytes,json=trafficRemainingBytes,proto3" json:"traffic_remaining_bytes,omitempty"`
	TrafficDisabled       bool   `protobuf:"varint,14,opt,name=traffic_disabled,json=trafficDisabled,proto3" json:"traffic_disabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_session_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Heartbeat) GetWallClockMs() int64 {
	if x != nil {
		return x.WallClockMs
	}
	return 0
}

func (x *Heartbeat) GetActiveStreams() uint32 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *Heartbeat) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Heartbeat) GetProtoFingerprint() string {
	if x != nil {
		return x.ProtoFingerprint
	}
	return ""
}

func (x *Heartbeat) GetSessionMode() string {
	if x != nil {
		return x.SessionMode
	}
	return ""
}

func (x *Heartbeat) GetControlPath() string {
	if x != nil {
		return x.ControlPath
	}
	return ""
}

func (x *Heartbeat) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Heartbeat) GetTransport() TransportMode {
	if x != nil {
		return x.Transport
	}
	return TransportMode_TRANSPORT_MODE_UNSPECIFIED
}

func (x *Heartbeat) GetTrafficPresent() bool {
	if x != nil {
		return x.TrafficPresent
	}
	return false
}

func (x *Heartbeat) GetTrafficLimitBytes() uint64 {
	if x != nil {
		return x.TrafficLimitBytes
	}
	return 0
}

func (x *Heartbeat) GetTrafficUsedBytes() uint64 {
	if x != nil {
		return x.TrafficUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetTrafficRemainingBytes() uint64 {
	if x != nil {
		return x.TrafficRemainingBytes
	}
	return 0
}

func (x *Heartbeat) GetTrafficDisabled() bool {
	if x != nil {
		return x.TrafficDisabled
	}
	return false
}

var File_proto_session_proto protoreflect.FileDescriptor

const file_proto_session_proto_rawDesc = "" +
	"\n" +
	"\x13proto/session.proto\x12\fsessionproto\"\xfa\x05\n" +
	"\vClientHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.sessionproto.ClientHelloTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\fR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\rR\bstreamId\x12L\n" +
	"\x13requested_transport\x18\x05 \x01(\x0e2\x1b.sessionproto.TransportModeR\x12requestedTransport\x12N\n" +
	"\x14supported_transports\x18\x06 \x03(\x0e2\x1b.sessionproto.TransportModeR\x13supportedTransports\x12T\n" +
	"\x15supported_tcp_flavors\x18\a \x03(\x0e2 .sessionproto.TcpTransportFlavorR\x13supportedTcpFlavors\x12R\n" +
	"\x14preferred_tcp_flavor\x18\b \x01(\x0e2 .sessionproto.TcpTransportFlavorR\x12preferredTcpFlavor\x12C\n" +
	"\rroom_exchange\x18\t \x01(\v2\x1e.sessionproto.RoomDataExchangeR\froomExchange\x12N\n" +
	"\x16supported_wrap_ciphers\x18\n" +
	" \x03(\x0e2\x18.sessionproto.WrapCipherR\x14supportedWrapCiphers\x12*\n" +
	"\x11wrap_key_proposal\x18\v \x01(\fR\x0fwrapKeyProposal\x12<\n" +
	"\tprovision\x18\f \x01(\v2\x1e.sessionproto.ProvisionRequestR\tprovision\x12\x1b\n" +
	"\tclient_id\x18\r \x01(\tR\bclientId\"x\n" +
	"\x10ProvisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\x12\x12\n" +
	"\x04hwid\x18\x03 \x01(\tR\x04hwid\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\rR\tlocalPort\"X\n" +
	"\x11ProvisionResponse\x12-\n" +
	"\x02wg\x18\x01 \x01(\v2\x1d.sessionproto.WireguardConfigR\x02wg\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xca\x01\n" +
	"\x0fWireguardConfig\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12*\n" +
	"\x11server_public_key\x18\x04 \x01(\tR\x0fserverPublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x01(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\"\xe1\x01\n" +
	"\x10RoomDataExchange\x126\n" +
	"\bprovider\x18\x01 \x01(\x0e2\x1a.sessionproto.RoomProviderR\bprovider\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\ve2e_enabled\x18\x04 \x01(\bR\n" +
	"e2eEnabled\x12\x1d\n" +
	"\n" +
	"e2e_secret\x18\x05 \x01(\fR\te2eSecret\x12\x19\n" +
	"\broom_ids\x18\x06 \x03(\tR\aroomIds\"?\n" +
	"\vRoomDataAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb0\x04\n" +
	"\vServerHello\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fmu_supported\x18\x02 \x01(\bR\vmuSupported\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12>\n" +
	"\x1bcontrol_heartbeat_supported\x18\x04 \x01(\bR\x19controlHeartbeatSupported\x12J\n" +
	"\x12selected_transport\x18\x05 \x01(\x0e2\x1b.sessionproto.TransportModeR\x11selectedTransport\x12N\n" +
	"\x14supported_transports\x18\x06 \x03(\x0e2\x1b.sessionproto.TransportModeR\x13supportedTransports\x12T\n" +
	"\x15supported_tcp_flavors\x18\a \x03(\x0e2 .sessionproto.TcpTransportFlavorR\x13supportedTcpFlavors\x12P\n" +
	"\x13selected_tcp_flavor\x18\b \x01(\x0e2 .sessionproto.TcpTransportFlavorR\x11selectedTcpFlavor\x12J\n" +
	"\x14selected_wrap_cipher\x18\t \x01(\x0e2\x18.sessionproto.WrapCipherR\x12selectedWrapCipher\"\xbc\x04\n" +
	"\tHeartbeat\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\"\n" +
	"\rwall_clock_ms\x18\x02 \x01(\x03R\vwallClockMs\x12%\n" +
	"\x0eactive_streams\x18\x03 \x01(\rR\ractiveStreams\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12+\n" +
	"\x11proto_fingerprint\x18\x05 \x01(\tR\x10protoFingerprint\x12!\n" +
	"\fsession_mode\x18\x06 \x01(\tR\vsessionMode\x12!\n" +
	"\fcontrol_path\x18\a \x01(\tR\vcontrolPath\x12\x1a\n" +
	"\bprovider\x18\b \x01(\tR\bprovider\x129\n" +
	"\ttransport\x18\t \x01(\x0e2\x1b.sessionproto.TransportModeR\ttransport\x12'\n" +
	"\x0ftraffic_present\x18\n" +
	" \x01(\bR\x0etrafficPresent\x12.\n" +
	"\x13traffic_limit_bytes\x18\v \x01(\x04R\x11trafficLimitBytes\x12,\n" +
	"\x12traffic_used_bytes\x18\f \x01(\x04R\x10trafficUsedBytes\x126\n" +
	"\x17traffic_remaining_bytes\x18\r \x01(\x04R\x15trafficRemainingBytes\x12)\n" +
	"\x10traffic_disabled\x18\x0e \x01(\bR\x0ftrafficDisabled*\xb6\x01\n" +
	"\x0fClientHelloType\x12!\n" +
	"\x1dCLIENT_HELLO_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CLIENT_HELLO_TYPE_PROBE\x10\x01\x12\x1d\n" +
	"\x19CLIENT_HELLO_TYPE_SESSION\x10\x02\x12#\n" +
	"\x1fCLIENT_HELLO_TYPE_ROOM_EXCHANGE\x10\x03\x12\x1f\n" +
	"\x1bCLIENT_HELLO_TYPE_PROVISION\x10\x04*d\n" +
	"\rTransportMode\x12\x1e\n" +
	"\x1aTRANSPORT_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSPORT_MODE_DATAGRAM\x10\x01\x12\x16\n" +
	"\x12TRANSPORT_MODE_TCP\x10\x02*\x8a\x01\n" +
	"\x12TcpTransportFlavor\x12$\n" +
	" TCP_TRANSPORT_FLAVOR_UNSPECIFIED\x10\x00\x12(\n" +
	"$TCP_TRANSPORT_FLAVOR_LEGACY_KCP_SMUX\x10\x01\x12$\n" +
	" TCP_TRANSPORT_FLAVOR_DIRECT_SMUX\x10\x02*\x89\x01\n" +
	"\n" +
	"WrapCipher\x12\x1b\n" +
	"\x17WRAP_CIPHER_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WRAP_CIPHER_NONE\x10\x01\x12 \n" +
	"\x1cWRAP_CIPHER_SRTP_AES_256_GCM\x10\x02\x12&\n" +
	"\"WRAP_CIPHER_SRTP_CHACHA20_POLY1305\x10\x03*J\n" +
	"\fRoomProvider\x12\x1d\n" +
	"\x19ROOM_PROVIDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ROOM_PROVIDER_WB_STREAM\x10\x01B=Z;github.com/cacggghp/vk-turn-proxy/sessionproto;sessionprotob\x06proto3"

var (
	file_proto_session_proto_rawDescOnce sync.Once
	file_proto_session_proto_rawDescData []byte
)

func file_proto_session_proto_rawDescGZIP() []byte {
	file_proto_session_proto_rawDescOnce.Do(func() {
		file_proto_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)))
	})
	return file_proto_session_proto_rawDescData
}

var file_proto_session_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_session_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_session_proto_goTypes = []any{
	(ClientHelloType)(0),      // 0: sessionproto.ClientHelloType
	(TransportMode)(0),        // 1: sessionproto.TransportMode
	(TcpTransportFlavor)(0),   // 2: sessionproto.TcpTransportFlavor
	(WrapCipher)(0),           // 3: sessionproto.WrapCipher
	(RoomProvider)(0),         // 4: sessionproto.RoomProvider
	(*ClientHello)(nil),       // 5: sessionproto.ClientHello
	(*ProvisionRequest)(nil),  // 6: sessionproto.ProvisionRequest
	(*ProvisionResponse)(nil), // 7: sessionproto.ProvisionResponse
	(*WireguardConfig)(nil),   // 8: sessionproto.WireguardConfig
	(*RoomDataExchange)(nil),  // 9: sessionproto.RoomDataExchange
	(*RoomDataAck)(nil),       // 10: sessionproto.RoomDataAck
	(*ServerHello)(nil),       // 11: sessionproto.ServerHello
	(*Heartbeat)(nil),         // 12: sessionproto.Heartbeat
}
var file_proto_session_proto_depIdxs = []int32{
	0,  // 0: sessionproto.ClientHello.type:type_name -> sessionproto.ClientHelloType
	1,  // 1: sessionproto.ClientHello.requested_transport:type_name -> sessionproto.TransportMode
	1,  // 2: sessionproto.ClientHello.supported_transports:type_name -> sessionproto.TransportMode
	2,  // 3: sessionproto.ClientHello.supported_tcp_flavors:type_name -> sessionproto.TcpTransportFlavor
	2,  // 4: sessionproto.ClientHello.preferred_tcp_flavor:type_name -> sessionproto.TcpTransportFlavor
	9,  // 5: sessionproto.ClientHello.room_exchange:type_name -> sessionproto.RoomDataExchange
	3,  // 6: sessionproto.ClientHello.supported_wrap_ciphers:type_name -> sessionproto.WrapCipher
	6,  // 7: sessionproto.ClientHello.provision:type_name -> sessionproto.ProvisionRequest
	8,  // 8: sessionproto.ProvisionResponse.wg:type_name -> sessionproto.WireguardConfig
	4,  // 9: sessionproto.RoomDataExchange.provider:type_name -> sessionproto.RoomProvider
	1,  // 10: sessionproto.ServerHello.selected_transport:type_name -> sessionproto.TransportMode
	1,  // 11: sessionproto.ServerHello.supported_transports:type_name -> sessionproto.TransportMode
	2,  // 12: sessionproto.ServerHello.supported_tcp_flavors:type_name -> sessionproto.TcpTransportFlavor
	2,  // 13: sessionproto.ServerHello.selected_tcp_flavor:type_name -> sessionproto.TcpTransportFlavor
	3,  // 14: sessionproto.ServerHello.selected_wrap_cipher:type_name -> sessionproto.WrapCipher
	1,  // 15: sessionproto.Heartbeat.transport:type_name -> sessionproto.TransportMode
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_session_proto_init() }
func file_proto_session_proto_init() {
	if File_proto_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_session_proto_rawDesc), len(file_proto_session_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_session_proto_goTypes,
		DependencyIndexes: file_proto_session_proto_depIdxs,
		EnumInfos:         file_proto_session_proto_enumTypes,
		MessageInfos:      file_proto_session_proto_msgTypes,
	}.Build()
	File_proto_session_proto = out.File
	file_proto_session_proto_goTypes = nil
	file_proto_session_proto_depIdxs = nil
}
